const visaTypesSeed = [
  {
    countrySlug: "usa",
    countryName: "USA",
    visaTypeSlug: "f1",
    visaTypeName: "F1",
    title: "USA F1 Visa",
    badge: "USA • F1 Visa",
    subtitle:
      "Study in the United States with structured visa guidance, document support, and interview preparation.",
    heroImage:
      "https://images.unsplash.com/photo-1485738422979-f5c462d49f74?q=80&w=1200&auto=format&fit=crop",
    iconKey: "graduation-cap",
    serviceHighlights: [
      { title: "Documentation Support", description: "Structured checklist and quality review", iconKey: "folder-check" },
      { title: "Interview Readiness", description: "Mock interview support and profile alignment", iconKey: "messages-square" },
    ],
    eligibility: [
      "Accepted by a recognized academic institution",
      "Sufficient financial support for tuition and living",
      "Clear academic intent",
    ],
    requiredDocs: [
      "Valid passport",
      "Photograph",
      "DS-160 confirmation",
      "Admission documents",
      "Financial proof",
    ],
    process: [
      "Consultation",
      "Document collection",
      "Application preparation",
      "Interview preparation",
      "Submission and follow-up",
    ],
    timeline: ["Consultation", "Document Preparation", "Application Review", "Interview", "Decision Awaited"],
    faqs: [
      { question: "What is F1 visa used for?", answer: "F1 is generally used for academic study in the USA." },
      { question: "Is financial proof required?", answer: "Yes, financial capacity documents are generally required." },
    ],
    ctaTitle: "Ready to Start Your USA F1 Visa Application?",
    ctaText: "Get expert guidance for documentation and interview preparation.",
    seoTitle: "USA F1 Visa Guidance",
    seoDescription: "Complete support for USA F1 student visa process.",
    metaKeywords: ["usa f1 visa", "student visa usa", "f1 documentation"],
    isActive: true,
    isFeatured: false,
    sortOrder: 1,
  },
  {
    countrySlug: "usa",
    countryName: "USA",
    visaTypeSlug: "f2",
    visaTypeName: "F2",
    title: "USA F2 Visa",
    badge: "USA • F2 Visa",
    subtitle: "Support for dependent visa applications of eligible family members.",
    heroImage:
      "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?q=80&w=1200&auto=format&fit=crop",
    iconKey: "users",
    serviceHighlights: [
      { title: "Relationship File Review", description: "Accurate dependent eligibility documentation", iconKey: "shield-check" },
    ],
    eligibility: ["Eligible spouse or child of an F1 holder", "Valid relationship documentation"],
    requiredDocs: ["Passport", "Relationship proof", "Principal visa records", "DS-160 confirmation"],
    process: ["Eligibility check", "Document prep", "Application", "Interview readiness", "Follow-up"],
    timeline: ["Consultation", "Document Review", "Application", "Interview", "Decision"],
    faqs: [
      { question: "Who can apply for F2?", answer: "Eligible spouse and qualifying children of F1 holders." },
    ],
    ctaTitle: "Start Your USA F2 Visa Application",
    ctaText: "Get structured support for dependent visa filing.",
    seoTitle: "USA F2 Dependent Visa Support",
    seoDescription: "Complete guidance for F2 dependent visa applications.",
    metaKeywords: ["usa f2 visa", "dependent visa usa"],
    isActive: true,
    isFeatured: false,
    sortOrder: 2,
  },
  {
    countrySlug: "usa",
    countryName: "USA",
    visaTypeSlug: "b1-b2",
    visaTypeName: "B1/B2",
    title: "USA B1/B2 Visa",
    badge: "USA • B1/B2 Visa",
    subtitle: "Support for business, tourism, and family visit travel.",
    heroImage:
      "https://images.unsplash.com/photo-1501594907352-04cda38ebc29?q=80&w=1200&auto=format&fit=crop",
    iconKey: "briefcase",
    serviceHighlights: [
      { title: "Purpose Mapping", description: "Align travel purpose and supporting file", iconKey: "briefcase" },
    ],
    eligibility: ["Clear short-trip purpose", "Supporting travel and financial records"],
    requiredDocs: ["Passport", "DS-160", "Travel purpose letter", "Financial proof"],
    process: ["Category review", "Documents", "Application", "Interview prep", "Decision"],
    timeline: ["Consultation", "Documentation", "Application", "Interview", "Decision"],
    faqs: [
      { question: "What is B1/B2 used for?", answer: "Usually for short business or tourism visits." },
    ],
    ctaTitle: "Start Your USA B1/B2 Visa Application",
    ctaText: "Get practical support for documentation and interview readiness.",
    seoTitle: "USA B1 B2 Visa Support",
    seoDescription: "Business and tourist visa assistance for USA travel.",
    metaKeywords: ["usa b1 b2 visa", "usa tourist visa"],
    isActive: true,
    isFeatured: false,
    sortOrder: 3,
  },
  {
    countrySlug: "canada",
    countryName: "Canada",
    visaTypeSlug: "visitor",
    visaTypeName: "Visitor",
    title: "Canada Visitor Visa",
    badge: "Canada • Visitor Visa",
    subtitle: "Structured support for tourism, family visits, and short travel.",
    heroImage:
      "https://images.unsplash.com/photo-1517935706615-2717063c2225?q=80&w=1200&auto=format&fit=crop",
    iconKey: "plane",
    serviceHighlights: [
      { title: "Travel File Structuring", description: "Purpose clarity and supporting records", iconKey: "file-text" },
    ],
    eligibility: ["Clear travel intent", "Sufficient funds"],
    requiredDocs: ["Passport", "Travel plan", "Financial proof", "Stay details"],
    process: ["Consultation", "File preparation", "Application", "Submission", "Decision"],
    timeline: ["Consultation", "Documentation", "Review", "Submission", "Decision"],
    faqs: [
      { question: "Do I need financial proof?", answer: "Yes, financial support documents are typically required." },
    ],
    ctaTitle: "Start Your Canada Visitor Visa Application",
    ctaText: "Get guided support for a stronger visitor visa file.",
    seoTitle: "Canada Visitor Visa Guidance",
    seoDescription: "Support for Canada visitor visa documentation and process.",
    metaKeywords: ["canada visitor visa", "canada tourist visa"],
    isActive: true,
    isFeatured: false,
    sortOrder: 1,
  },
  {
    countrySlug: "uk",
    countryName: "United Kingdom",
    visaTypeSlug: "standard-visitor",
    visaTypeName: "Standard Visitor",
    title: "UK Standard Visitor Visa",
    badge: "UK • Standard Visitor Visa",
    subtitle: "Support for tourism and short-stay travel to the UK.",
    heroImage:
      "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?q=80&w=1200&auto=format&fit=crop",
    iconKey: "plane",
    serviceHighlights: [
      { title: "Application Quality Review", description: "Consistency checks before submission", iconKey: "shield-check" },
    ],
    eligibility: ["Short-stay purpose", "Financial and stay evidence"],
    requiredDocs: ["Passport", "Travel purpose", "Funds proof", "Accommodation details"],
    process: ["Consultation", "Document collection", "Application prep", "Submission", "Decision"],
    timeline: ["Consultation", "Documentation", "Review", "Submission", "Decision"],
    faqs: [
      { question: "Can I use this visa for tourism?", answer: "Yes, this route supports short tourism travel." },
    ],
    ctaTitle: "Start Your UK Visitor Visa Application",
    ctaText: "Get support for a complete and consistent application file.",
    seoTitle: "UK Standard Visitor Visa Support",
    seoDescription: "Guidance for UK short-stay visitor visa applications.",
    metaKeywords: ["uk visitor visa", "uk standard visitor"],
    isActive: true,
    isFeatured: false,
    sortOrder: 1,
  },
  {
    countrySlug: "australia",
    countryName: "Australia",
    visaTypeSlug: "visitor",
    visaTypeName: "Visitor",
    title: "Australia Visitor Visa",
    badge: "Australia • Visitor Visa",
    subtitle: "Guidance for short-stay visitor visa applications to Australia.",
    heroImage:
      "https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?q=80&w=1200&auto=format&fit=crop",
    iconKey: "plane",
    serviceHighlights: [
      { title: "Document Planning", description: "Checklist-driven preparation", iconKey: "folder-check" },
    ],
    eligibility: ["Clear short-stay purpose", "Supporting financial records"],
    requiredDocs: ["Passport", "Travel plan", "Financial proof", "Stay details"],
    process: ["Consultation", "Documentation", "Application prep", "Submission", "Decision"],
    timeline: ["Consultation", "Documents", "Review", "Submission", "Decision"],
    faqs: [
      { question: "Can family invitation help?", answer: "Yes, invitation details can strengthen purpose clarity." },
    ],
    ctaTitle: "Start Your Australia Visitor Visa Application",
    ctaText: "Get practical support for documents and application flow.",
    seoTitle: "Australia Visitor Visa Support",
    seoDescription: "End-to-end support for Australia visitor visa filing.",
    metaKeywords: ["australia visitor visa", "australia tourist visa"],
    isActive: true,
    isFeatured: false,
    sortOrder: 1,
  },
  {
    countrySlug: "schengen",
    countryName: "Schengen",
    visaTypeSlug: "tourist",
    visaTypeName: "Tourist",
    title: "Schengen Tourist Visa",
    badge: "Schengen • Tourist Visa",
    subtitle: "Visa support for tourism and leisure travel across Schengen destinations.",
    heroImage:
      "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?q=80&w=1200&auto=format&fit=crop",
    iconKey: "plane",
    serviceHighlights: [
      { title: "Itinerary Validation", description: "Trip plan and stay consistency review", iconKey: "clock-3" },
    ],
    eligibility: ["Tourism purpose", "Financial and itinerary proof"],
    requiredDocs: ["Passport", "Itinerary", "Insurance", "Funds proof", "Stay proof"],
    process: ["Consultation", "Document prep", "Application", "Biometrics", "Decision"],
    timeline: ["Consultation", "Documents", "Review", "Submission", "Decision"],
    faqs: [
      { question: "Is travel insurance required?", answer: "It may be required depending on your route and embassy rules." },
    ],
    ctaTitle: "Start Your Schengen Tourist Visa Application",
    ctaText: "Get expert support for itinerary and embassy-ready documentation.",
    seoTitle: "Schengen Tourist Visa Guidance",
    seoDescription: "Structured support for Schengen tourist visa applications.",
    metaKeywords: ["schengen tourist visa", "schengen visa"],
    isActive: true,
    isFeatured: false,
    sortOrder: 1,
  },
  {
    countrySlug: "turkey",
    countryName: "Turkey",
    visaTypeSlug: "business",
    visaTypeName: "Business",
    title: "Turkey Business Visa",
    badge: "Turkey • Business Visa",
    subtitle: "Structured support for business travel and professional visits.",
    heroImage:
      "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?q=80&w=1200&auto=format&fit=crop",
    iconKey: "briefcase",
    serviceHighlights: [
      { title: "Business File Readiness", description: "Meeting purpose and invitation alignment", iconKey: "briefcase" },
    ],
    eligibility: ["Business purpose", "Supporting company records"],
    requiredDocs: ["Passport", "Business invitation", "Travel purpose note", "Funds proof"],
    process: ["Consultation", "Business documents", "Application prep", "Submission", "Decision"],
    timeline: ["Consultation", "Documents", "Review", "Submission", "Decision"],
    faqs: [
      { question: "Is invitation required?", answer: "Business support documents are often important for this route." },
    ],
    ctaTitle: "Start Your Turkey Business Visa Application",
    ctaText: "Get practical support for business travel documentation.",
    seoTitle: "Turkey Business Visa Support",
    seoDescription: "Guided support for Turkey business visa applications.",
    metaKeywords: ["turkey business visa", "business travel turkey"],
    isActive: true,
    isFeatured: false,
    sortOrder: 1,
  },
];

module.exports = { visaTypesSeed };
